### ISSUE TITLE
Add travis

### ISSUE THREAD

**Issue by ElliotAOram** [marshallmcdonnell/mantid_total_scattering#5]
In order to have some continuous integration in the code base we should add travis to run builds for regression testing. Currently the repo has a system test and unit tests. The main difficulty will be making mantid run successful within travis. Marshall has a docker container with a mantid image we can use so this will get us part of the way there. the good news is that we do not need to validate building mantid - only use it (so in the worst case scenario we can download and install it)

**Comment by marshallmcdonnell** [comment]
The Mantid dockefile is in the project as `dockerfiles/Mantid_Dockerfil`. 

The project dockerfile is the main `Dockerfile` in the top-level of the project. It just pulls from the `marshallmcdonnell/mantid` docker image from DockerHub (which was created from the `Mantid_Dockerfile`) and then adds this project. This is for speed since building Mantid can be a very long process.

**Comment by marshallmcdonnell** [comment]
Closed by #8
